# yaml-language-server: $schema=https://schema.zeabur.app/template.json
apiVersion: zeabur.com/v1
kind: Template
metadata:
    name: moltbot Browser Sandbox
spec:
    description: |
      Headless Chromium browser sandbox that can be controlled via Chrome DevTools Protocol (CDP). Use this with moltbot or other services that need browser automation capabilities.
    icon: https://raw.githubusercontent.com/moltbot/moltbot/main/docs/assets/pixel-lobster.svg
    tags:
      - Browser
      - Automation
      - Chromium
      - CDP
    resourceUsage:
      cpu: 1
      memory: 1024

    readme: |
      # moltbot Browser Sandbox
      A headless Chromium browser that can be controlled via Chrome DevTools Protocol (CDP).

      ## Use Cases
      - Browser automation with moltbot
      - Web scraping
      - Automated testing
      - Screenshot services

      ## How to Connect
      Other services in the same Zeabur project can connect via:
      ```
      http://moltbot-sandbox-browser:9222
      ```

      ## CDP Endpoints
      - `GET /json/version` - Browser version info
      - `GET /json/list` - List open tabs
      - `GET /json/new?url=<url>` - Open new tab
      - WebSocket connections for DevTools protocol

      ## Configuration for moltbot

      **Option 1: CLI commands** (via Zeabur Command):
      ```bash
      moltbot config set browser.enabled true
      moltbot config set browser.attachOnly true
      moltbot config set browser.profiles.clawd.cdpUrl "http://moltbot-sandbox-browser:9222"
      ```

      **Option 2: Edit config file** - Add to `clawdbot.json`:
      ```json
      {
        "browser": {
          "enabled": true,
          "attachOnly": true,
          "profiles": {
            "clawd": {
              "cdpUrl": "http://moltbot-sandbox-browser:9222"
            }
          }
        }
      }
      ```

      Restart the gateway to apply changes.

      ## Resources
      - **Recommended**: 1 vCPU, 1 GB RAM
      - **Heavy usage**: 2 vCPU, 2 GB RAM

      ## Ignorable Errors
      The following error messages in logs are normal and can be safely ignored:
      - `Failed to connect to the bus` - No D-Bus in container (expected)
      - `Failed to adjust OOM score` - Permission limitation (doesn't affect functionality)
      - `DEPRECATED_ENDPOINT` - Google Cloud Messaging not needed for headless mode

      ## Documentation
      - moltbot Template: https://zeabur.com/templates/VTZ4FX
      - moltbot Browser Tool: https://docs.molt.bot/tools/browser
      - GitHub: https://github.com/canyugs/moltbot-sandbox-browser

    services:
      - name: moltbot-sandbox-browser
        icon: https://raw.githubusercontent.com/moltbot/moltbot/main/docs/assets/pixel-lobster.svg
        template: PREBUILT
        spec:
          source:
            image: ghcr.io/canyugs/moltbot-sandbox-browser:main
          ports:
          - id: cdp
            port: 9222
            type: TCP
          healthCheck:
            type: TCP
            port: cdp
          env:
            CLAWDBOT_BROWSER_HEADLESS:
              default: "1"
            CLAWDBOT_BROWSER_CDP_PORT:
              default: "9222"
              readonly: true

localization:
  zh-TW:
    name: moltbot 瀏覽器沙盒
    description: |
      無頭 Chromium 瀏覽器沙盒，可透過 Chrome DevTools Protocol (CDP) 控制。可搭配 moltbot 或其他需要瀏覽器自動化功能的服務使用。
    readme: |
      # moltbot 瀏覽器沙盒
      可透過 Chrome DevTools Protocol (CDP) 控制的無頭 Chromium 瀏覽器。

      ## 使用場景
      - 搭配 moltbot 進行瀏覽器自動化
      - 網頁爬蟲
      - 自動化測試
      - 截圖服務

      ## 連線方式
      同一個 Zeabur 專案中的其他服務可透過以下方式連線：
      ```
      http://moltbot-sandbox-browser:9222
      ```

      ## CDP 端點
      - `GET /json/version` - 瀏覽器版本資訊
      - `GET /json/list` - 列出已開啟的分頁
      - `GET /json/new?url=<url>` - 開啟新分頁
      - WebSocket 連線用於 DevTools 協議

      ## moltbot 設定

      **方式一：CLI 指令**（透過 Zeabur 指令）：
      ```bash
      moltbot config set browser.enabled true
      moltbot config set browser.attachOnly true
      moltbot config set browser.profiles.clawd.cdpUrl "http://moltbot-sandbox-browser:9222"
      ```

      **方式二：編輯設定檔** - 在 `clawdbot.json` 中加入：
      ```json
      {
        "browser": {
          "enabled": true,
          "attachOnly": true,
          "profiles": {
            "clawd": {
              "cdpUrl": "http://moltbot-sandbox-browser:9222"
            }
          }
        }
      }
      ```

      完成後重新啟動 gateway 以套用設定。

      ## 資源需求
      - **建議配置**：1 vCPU、1 GB RAM
      - **大量使用**：2 vCPU、2 GB RAM

      ## 可忽略的錯誤
      以下日誌中的錯誤訊息是正常的，可以安全忽略：
      - `Failed to connect to the bus` - 容器內沒有 D-Bus（正常現象）
      - `Failed to adjust OOM score` - 權限限制（不影響功能）
      - `DEPRECATED_ENDPOINT` - 無頭模式不需要 Google Cloud Messaging

      ## 文件
      - moltbot 模板：https://zeabur.com/templates/VTZ4FX
      - moltbot 瀏覽器工具：https://docs.molt.bot/tools/browser
      - GitHub：https://github.com/canyugs/moltbot-sandbox-browser

  zh-CN:
    name: moltbot 浏览器沙盒
    description: |
      无头 Chromium 浏览器沙盒，可通过 Chrome DevTools Protocol (CDP) 控制。可搭配 moltbot 或其他需要浏览器自动化功能的服务使用。
    readme: |
      # moltbot 浏览器沙盒
      可通过 Chrome DevTools Protocol (CDP) 控制的无头 Chromium 浏览器。

      ## 使用场景
      - 搭配 moltbot 进行浏览器自动化
      - 网页爬虫
      - 自动化测试
      - 截图服务

      ## 连接方式
      同一个 Zeabur 项目中的其他服务可通过以下方式连接：
      ```
      http://moltbot-sandbox-browser:9222
      ```

      ## CDP 端点
      - `GET /json/version` - 浏览器版本信息
      - `GET /json/list` - 列出已打开的标签页
      - `GET /json/new?url=<url>` - 打开新标签页
      - WebSocket 连接用于 DevTools 协议

      ## moltbot 配置

      **方式一：CLI 命令**（通过 Zeabur 命令）：
      ```bash
      moltbot config set browser.enabled true
      moltbot config set browser.attachOnly true
      moltbot config set browser.profiles.clawd.cdpUrl "http://moltbot-sandbox-browser:9222"
      ```

      **方式二：编辑配置文件** - 在 `clawdbot.json` 中添加：
      ```json
      {
        "browser": {
          "enabled": true,
          "attachOnly": true,
          "profiles": {
            "clawd": {
              "cdpUrl": "http://moltbot-sandbox-browser:9222"
            }
          }
        }
      }
      ```

      完成后重新启动 gateway 以应用设置。

      ## 资源需求
      - **建议配置**：1 vCPU、1 GB RAM
      - **大量使用**：2 vCPU、2 GB RAM

      ## 可忽略的错误
      以下日志中的错误信息是正常的，可以安全忽略：
      - `Failed to connect to the bus` - 容器内没有 D-Bus（正常现象）
      - `Failed to adjust OOM score` - 权限限制（不影响功能）
      - `DEPRECATED_ENDPOINT` - 无头模式不需要 Google Cloud Messaging

      ## 文档
      - moltbot 模板：https://zeabur.com/templates/VTZ4FX
      - moltbot 浏览器工具：https://docs.molt.bot/tools/browser
      - GitHub：https://github.com/canyugs/moltbot-sandbox-browser

  ja:
    name: moltbot ブラウザサンドボックス
    description: |
      Chrome DevTools Protocol (CDP) で制御可能なヘッドレス Chromium ブラウザサンドボックス。moltbot やブラウザ自動化が必要な他のサービスと組み合わせて使用できます。
    readme: |
      # moltbot ブラウザサンドボックス
      Chrome DevTools Protocol (CDP) で制御可能なヘッドレス Chromium ブラウザ。

      ## ユースケース
      - moltbot でのブラウザ自動化
      - ウェブスクレイピング
      - 自動テスト
      - スクリーンショットサービス

      ## 接続方法
      同じ Zeabur プロジェクト内の他のサービスから以下で接続できます：
      ```
      http://moltbot-sandbox-browser:9222
      ```

      ## CDP エンドポイント
      - `GET /json/version` - ブラウザバージョン情報
      - `GET /json/list` - 開いているタブの一覧
      - `GET /json/new?url=<url>` - 新しいタブを開く
      - DevTools プロトコル用 WebSocket 接続

      ## moltbot 設定

      **方法1：CLI コマンド**（Zeabur コマンド経由）：
      ```bash
      moltbot config set browser.enabled true
      moltbot config set browser.attachOnly true
      moltbot config set browser.profiles.clawd.cdpUrl "http://moltbot-sandbox-browser:9222"
      ```

      **方法2：設定ファイルを編集** - `clawdbot.json` に追加：
      ```json
      {
        "browser": {
          "enabled": true,
          "attachOnly": true,
          "profiles": {
            "clawd": {
              "cdpUrl": "http://moltbot-sandbox-browser:9222"
            }
          }
        }
      }
      ```

      完了後、gateway を再起動して設定を適用してください。

      ## リソース要件
      - **推奨構成**：1 vCPU、1 GB RAM
      - **高負荷使用**：2 vCPU、2 GB RAM

      ## 無視できるエラー
      以下のログエラーメッセージは正常であり、安全に無視できます：
      - `Failed to connect to the bus` - コンテナ内に D-Bus がない（想定通り）
      - `Failed to adjust OOM score` - 権限の制限（機能に影響なし）
      - `DEPRECATED_ENDPOINT` - ヘッドレスモードでは Google Cloud Messaging 不要

      ## ドキュメント
      - moltbot テンプレート：https://zeabur.com/templates/VTZ4FX
      - moltbot ブラウザツール：https://docs.molt.bot/tools/browser
      - GitHub：https://github.com/canyugs/moltbot-sandbox-browser

  id:
    name: moltbot Browser Sandbox
    description: |
      Sandbox browser Chromium headless yang dapat dikontrol melalui Chrome DevTools Protocol (CDP). Gunakan dengan moltbot atau layanan lain yang membutuhkan kemampuan otomatisasi browser.
    readme: |
      # moltbot Browser Sandbox
      Browser Chromium headless yang dapat dikontrol melalui Chrome DevTools Protocol (CDP).

      ## Kasus Penggunaan
      - Otomatisasi browser dengan moltbot
      - Web scraping
      - Pengujian otomatis
      - Layanan screenshot

      ## Cara Menghubungkan
      Layanan lain dalam proyek Zeabur yang sama dapat terhubung melalui:
      ```
      http://moltbot-sandbox-browser:9222
      ```

      ## Endpoint CDP
      - `GET /json/version` - Info versi browser
      - `GET /json/list` - Daftar tab yang terbuka
      - `GET /json/new?url=<url>` - Buka tab baru
      - Koneksi WebSocket untuk protokol DevTools

      ## Konfigurasi untuk moltbot

      **Opsi 1: Perintah CLI** (melalui Zeabur Command):
      ```bash
      moltbot config set browser.enabled true
      moltbot config set browser.attachOnly true
      moltbot config set browser.profiles.clawd.cdpUrl "http://moltbot-sandbox-browser:9222"
      ```

      **Opsi 2: Edit file konfigurasi** - Tambahkan ke `clawdbot.json`:
      ```json
      {
        "browser": {
          "enabled": true,
          "attachOnly": true,
          "profiles": {
            "clawd": {
              "cdpUrl": "http://moltbot-sandbox-browser:9222"
            }
          }
        }
      }
      ```

      Setelah selesai, restart gateway untuk menerapkan pengaturan.

      ## Kebutuhan Sumber Daya
      - **Rekomendasi**: 1 vCPU, 1 GB RAM
      - **Penggunaan berat**: 2 vCPU, 2 GB RAM

      ## Error yang Dapat Diabaikan
      Pesan error berikut di log adalah normal dan dapat diabaikan dengan aman:
      - `Failed to connect to the bus` - Tidak ada D-Bus di container (normal)
      - `Failed to adjust OOM score` - Batasan izin (tidak mempengaruhi fungsi)
      - `DEPRECATED_ENDPOINT` - Google Cloud Messaging tidak diperlukan untuk mode headless

      ## Dokumentasi
      - Template moltbot: https://zeabur.com/templates/VTZ4FX
      - moltbot Browser Tool: https://docs.molt.bot/tools/browser
      - GitHub: https://github.com/canyugs/moltbot-sandbox-browser

  es:
    name: moltbot Browser Sandbox
    description: |
      Sandbox de navegador Chromium headless que puede ser controlado a través del Chrome DevTools Protocol (CDP). Úsalo con moltbot u otros servicios que necesiten capacidades de automatización de navegador.
    readme: |
      # moltbot Browser Sandbox
      Navegador Chromium headless que puede ser controlado a través del Chrome DevTools Protocol (CDP).

      ## Casos de Uso
      - Automatización de navegador con moltbot
      - Web scraping
      - Pruebas automatizadas
      - Servicios de captura de pantalla

      ## Cómo Conectar
      Otros servicios en el mismo proyecto de Zeabur pueden conectarse a través de:
      ```
      http://moltbot-sandbox-browser:9222
      ```

      ## Endpoints CDP
      - `GET /json/version` - Información de versión del navegador
      - `GET /json/list` - Listar pestañas abiertas
      - `GET /json/new?url=<url>` - Abrir nueva pestaña
      - Conexiones WebSocket para el protocolo DevTools

      ## Configuración para moltbot

      **Opción 1: Comandos CLI** (vía Zeabur Command):
      ```bash
      moltbot config set browser.enabled true
      moltbot config set browser.attachOnly true
      moltbot config set browser.profiles.clawd.cdpUrl "http://moltbot-sandbox-browser:9222"
      ```

      **Opción 2: Editar archivo de configuración** - Agregar a `clawdbot.json`:
      ```json
      {
        "browser": {
          "enabled": true,
          "attachOnly": true,
          "profiles": {
            "clawd": {
              "cdpUrl": "http://moltbot-sandbox-browser:9222"
            }
          }
        }
      }
      ```

      Después, reinicie el gateway para aplicar los cambios.

      ## Recursos
      - **Recomendado**: 1 vCPU, 1 GB RAM
      - **Uso intensivo**: 2 vCPU, 2 GB RAM

      ## Errores Ignorables
      Los siguientes mensajes de error en los logs son normales y pueden ignorarse de forma segura:
      - `Failed to connect to the bus` - No hay D-Bus en el contenedor (esperado)
      - `Failed to adjust OOM score` - Limitación de permisos (no afecta la funcionalidad)
      - `DEPRECATED_ENDPOINT` - Google Cloud Messaging no es necesario para el modo headless

      ## Documentación
      - Plantilla moltbot: https://zeabur.com/templates/VTZ4FX
      - moltbot Browser Tool: https://docs.molt.bot/tools/browser
      - GitHub: https://github.com/canyugs/moltbot-sandbox-browser
