# yaml-language-server: $schema=https://schema.zeabur.app/template.json
apiVersion: zeabur.com/v1
kind: Template
metadata:
    name: moltbot Browser Sandbox
spec:
    description: |
      Headless Chromium browser sandbox that can be controlled via Chrome DevTools Protocol (CDP). Use this with moltbot or other services that need browser automation capabilities.
    icon: https://raw.githubusercontent.com/moltbot/moltbot/main/docs/assets/pixel-lobster.svg
    tags:
      - Browser
      - Automation
      - Chromium
      - CDP
    resourceUsage:
      cpu: 1
      memory: 1024

    readme: |
      # moltbot Browser Sandbox
      A headless Chromium browser that can be controlled via Chrome DevTools Protocol (CDP).

      ## Use Cases
      - Browser automation with moltbot
      - Web scraping
      - Automated testing
      - Screenshot services

      ## How to Connect
      Other services in the same Zeabur project can connect via:
      ```
      http://moltbot-sandbox-browser:9222
      ```

      ## CDP Endpoints
      - `GET /json/version` - Browser version info
      - `GET /json/list` - List open tabs
      - `GET /json/new?url=<url>` - Open new tab
      - WebSocket connections for DevTools protocol

      ## Configuration for moltbot

      **Option 1: Config file** - Add to `clawdbot.json`:
      ```json
      {
        "browser": {
          "enabled": true,
          "attachOnly": true,
          "defaultProfile": "clawd",
          "profiles": {
            "clawd": {
              "cdpUrl": "http://moltbot-sandbox-browser:9222",
              "color": "#FF4500"
            }
          }
        }
      }
      ```

      **Option 2: CLI command**:
      ```bash
      moltbot browser create-profile --name clawd --cdp-url http://moltbot-sandbox-browser:9222 --color "#FF4500"
      ```

      ## Resources
      - **Recommended**: 1 vCPU, 1 GB RAM
      - **Heavy usage**: 2 vCPU, 2 GB RAM

      ## Ignorable Errors
      The following error messages in logs are normal and can be safely ignored:
      - `Failed to connect to the bus` - No D-Bus in container (expected)
      - `Failed to adjust OOM score` - Permission limitation (doesn't affect functionality)
      - `DEPRECATED_ENDPOINT` - Google Cloud Messaging not needed for headless mode

      ## Documentation
      - moltbot Browser Tool: https://docs.molt.bot/tools/browser
      - GitHub: https://github.com/canyugs/moltbot-sandbox-browser

    services:
      - name: moltbot-sandbox-browser
        icon: https://raw.githubusercontent.com/moltbot/moltbot/main/docs/assets/pixel-lobster.svg
        template: PREBUILT
        spec:
          source:
            image: ghcr.io/canyugs/moltbot-sandbox-browser:main
          ports:
          - id: cdp
            port: 9222
            type: TCP
          healthCheck:
            type: TCP
            port: cdp
          env:
            CLAWDBOT_BROWSER_HEADLESS:
              default: "1"
            CLAWDBOT_BROWSER_CDP_PORT:
              default: "9222"
              readonly: true

localization:
  zh-TW:
    name: moltbot 瀏覽器沙盒
    description: |
      無頭 Chromium 瀏覽器沙盒，可透過 Chrome DevTools Protocol (CDP) 控制。可搭配 moltbot 或其他需要瀏覽器自動化功能的服務使用。
    readme: |
      # moltbot 瀏覽器沙盒
      可透過 Chrome DevTools Protocol (CDP) 控制的無頭 Chromium 瀏覽器。

      ## 使用場景
      - 搭配 moltbot 進行瀏覽器自動化
      - 網頁爬蟲
      - 自動化測試
      - 截圖服務

      ## 連線方式
      同一個 Zeabur 專案中的其他服務可透過以下方式連線：
      ```
      http://moltbot-sandbox-browser:9222
      ```

      ## CDP 端點
      - `GET /json/version` - 瀏覽器版本資訊
      - `GET /json/list` - 列出已開啟的分頁
      - `GET /json/new?url=<url>` - 開啟新分頁
      - WebSocket 連線用於 DevTools 協議

      ## moltbot 設定

      **方式一：設定檔** - 在 `clawdbot.json` 中加入：
      ```json
      {
        "browser": {
          "enabled": true,
          "attachOnly": true,
          "defaultProfile": "clawd",
          "profiles": {
            "clawd": {
              "cdpUrl": "http://moltbot-sandbox-browser:9222",
              "color": "#FF4500"
            }
          }
        }
      }
      ```

      **方式二：CLI 命令**：
      ```bash
      moltbot browser create-profile --name clawd --cdp-url http://moltbot-sandbox-browser:9222 --color "#FF4500"
      ```

      ## 資源需求
      - **建議配置**：1 vCPU、1 GB RAM
      - **大量使用**：2 vCPU、2 GB RAM

      ## 可忽略的錯誤
      以下日誌中的錯誤訊息是正常的，可以安全忽略：
      - `Failed to connect to the bus` - 容器內沒有 D-Bus（正常現象）
      - `Failed to adjust OOM score` - 權限限制（不影響功能）
      - `DEPRECATED_ENDPOINT` - 無頭模式不需要 Google Cloud Messaging

      ## 文件
      - moltbot 瀏覽器工具：https://docs.molt.bot/tools/browser
      - GitHub：https://github.com/canyugs/moltbot-sandbox-browser

  zh-CN:
    name: moltbot 浏览器沙盒
    description: |
      无头 Chromium 浏览器沙盒，可通过 Chrome DevTools Protocol (CDP) 控制。可搭配 moltbot 或其他需要浏览器自动化功能的服务使用。
    readme: |
      # moltbot 浏览器沙盒
      可通过 Chrome DevTools Protocol (CDP) 控制的无头 Chromium 浏览器。

      ## 使用场景
      - 搭配 moltbot 进行浏览器自动化
      - 网页爬虫
      - 自动化测试
      - 截图服务

      ## 连接方式
      同一个 Zeabur 项目中的其他服务可通过以下方式连接：
      ```
      http://moltbot-sandbox-browser:9222
      ```

      ## CDP 端点
      - `GET /json/version` - 浏览器版本信息
      - `GET /json/list` - 列出已打开的标签页
      - `GET /json/new?url=<url>` - 打开新标签页
      - WebSocket 连接用于 DevTools 协议

      ## moltbot 配置

      **方式一：配置文件** - 在 `clawdbot.json` 中添加：
      ```json
      {
        "browser": {
          "enabled": true,
          "attachOnly": true,
          "defaultProfile": "clawd",
          "profiles": {
            "clawd": {
              "cdpUrl": "http://moltbot-sandbox-browser:9222",
              "color": "#FF4500"
            }
          }
        }
      }
      ```

      **方式二：CLI 命令**：
      ```bash
      moltbot browser create-profile --name clawd --cdp-url http://moltbot-sandbox-browser:9222 --color "#FF4500"
      ```

      ## 资源需求
      - **建议配置**：1 vCPU、1 GB RAM
      - **大量使用**：2 vCPU、2 GB RAM

      ## 可忽略的错误
      以下日志中的错误信息是正常的，可以安全忽略：
      - `Failed to connect to the bus` - 容器内没有 D-Bus（正常现象）
      - `Failed to adjust OOM score` - 权限限制（不影响功能）
      - `DEPRECATED_ENDPOINT` - 无头模式不需要 Google Cloud Messaging

      ## 文档
      - moltbot 浏览器工具：https://docs.molt.bot/tools/browser
      - GitHub：https://github.com/canyugs/moltbot-sandbox-browser
